### ISSUE TITLE
Do not allow strobe when lights are off

### ISSUE THREAD

**Issue by praseodym** [WISVCH/chue#19]
Currently strobe will function even if lights are turned off. Checking state first should fix this.

**Comment by gewoonrik** [comment]
I thought we could assume that all lights are always turned on?

**Comment by praseodym** [comment]
At CH, lights turn off when EWI is closed (through a timer on the bridge itself), so we better not allow strobe at those times.

**Comment by sanderploegsma** [comment]
> I thought we could assume that all lights are always turned on?

This also makes sure that when they are actually off, no-one will turn them on :stuck_out_tongue_winking_eye:
