### ISSUE TITLE
Update Hue SDK

### ISSUE THREAD

**Issue by praseodym** [WISVCH/chue#27]
https://github.com/PhilipsHue/PhilipsHueSDK-Java-MultiPlatform-Android/blob/master/CHANGELOG.md

**Comment by CantSleepAgain** [comment]
Hi there, I am beginner in Java, I know fine Java Core, algorythms(I have done about 100 tasks at algorythms) and I have done 3-4 small games(at InteliJ Idea Platform). Can you give me a work? I just need experience in creating projects.
