### ISSUE TITLE
Show current color of the lamps

### ISSUE THREAD

**Issue by jgadelange** [WISVCH/chue#3]
I want to be able to see the current color of the lamps on the web interface!

**Comment by sanderploegsma** [comment]
Test!

**Comment by RickWieman** [comment]
Can you actually retrieve the current color from the lamps, or should we keep their states in the `chue` application?

**Comment by praseodym** [comment]
Yes, e.g. https://github.com/WISVCH/chue/blob/de2d7763b1d489b458e07a9f13e5b0fe3c17ce72/src/main/java/ch/wisv/chue/HueService.java#L182-L183

**Comment by sanderploegsma** [comment]
By the way, I had some difficulties using `getLastKnownLightState`, see [here](https://github.com/WISVCH/chue/pull/5#issuecomment-86246655)
