### ISSUE TITLE
Bridge firmware update command

### ISSUE THREAD

**Issue by praseodym** [WISVCH/chue#38]
Bridge firmware can be updated with some REST calls, would be nice to implement support for that.

**Comment by praseodym** [comment]
We could also just [schedule a regular update](https://spring.io/guides/gs/scheduling-tasks/) instead of exposing this through the REST interface.

**Comment by RickWieman** [comment]
Or a combination of the two: scheduled updates, but also on user request (which could be nice if Philips releases new awesome features, and we want to deploy them instantaneously).

**Comment by praseodym** [comment]
If we check every day or so, it will be updated before we know it :p

**Comment by RickWieman** [comment]
That's also a possibility yes :blush:
